name: Docs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - run: npm i -g staticrypt
      - run: pip install -r requirements.docs.txt
      - run: mkdocs build
      - run: |
          mkdir -p build/site
          rsync -r --exclude="*.html" site build
          find ./site -type f -name "*.html" -exec staticrypt {} ShowComp -o ./build/{} -f docs/template.html \;
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v1.4.0
        with:
          keep_history: true
          target-branch: gh-pages
          build_dir: build/site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 