destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/kph-doc-pdf"
port: 4010
product: kph-doc
print_title: Technical Documentation for Kracum Performance Hall
print_subtitle: Kunwu Lyu
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: mydoc_sidebar
